JU-DEV-Bootcamps/ERAS-BE

src/Eras.Application/Mappers/HeatMapMapper.cs, src/Eras.Application/Models/HeatMap/HeatMapByComponentsResponseVm.cs
Add variable id to heatmap json response
=> Add variableId as property for heatmap data response

src/Eras.Api/Controllers/HeatMapController.cs, src/Eras.Application/Contracts/Persistence/IStudentRepository.cs, src/Eras.Application/Features/HeatMap/Queries/GetHeatMapDetailsByComponent/GetHeatMapDetailsByComponentQuery.cs, src/Eras.Application/Features/HeatMap/Queries/GetHeatMapDetailsByComponent/GetHeatMapDetailsByComponentQueryHandler.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/StudentRepository.cs
The query was updated to take n number of students.
=> Update: add limit in studentlist by component

test/Eras.Api.Tests/Controllers/HeatMapControllerTests.cs, test/Eras.Api.Tests/Eras.Api.Tests.csproj, test/Eras.Application.Tests/Eras.Application.Tests.csproj, test/Eras.Application.Tests/Heatmap/Queries/GetHeatmapByAllComponents/GetHeatMapDataByComponentsHandlerTest.cs, test/Eras.Application.Tests/Mocks/RepositoryHeatmapMock.cs
This PR creates unit test for the GetHeatMapByAllComponents feature. It includes test for the QueryHandler to validate the response behavior and results obtained with mockup data. Additionally, it includes tests for the Controller to validate the response status and the type of values returned upon executing the query.
Since the feature doesn't write any new data in the database, tests at the infrastructure layer were omitted.
* https://github.com/JU-DEV-Bootcamps/ERAS-BE/issues/96
=> Test(heatmap): Unit tests for Query Handler and Controller

.github/workflows/pr_workflow.yaml, .github/workflows/push_workflow.yaml, .github/workflows/workflow.yaml
This PR adds the code coverage configuration with a minimum threshold (10% of code lines) and modifies the workflow to control this metric. It also creates another workflow that is triggered only when PRs are created to test with coverage control and complete a building image process to check for any errors.
The original workflow with the test and package jobs is now only triggered when the changes are pushed to the main branch. Additionally, a step is added in the test (now coverage) job to upload the created coverage report and make it available for download and review.
* https://github.com/JU-DEV-Bootcamps/ERAS-BE/issues/105
=> CI: Code coverage in GitHub Action

src/Eras.Api/Controllers/PollInstanceController.cs, src/Eras.Application/Contracts/Persistence/IPollCohortRepository.cs, src/Eras.Application/Contracts/Persistence/IPollInstanceRepository.cs, src/Eras.Application/Features/PollInstances/Queries/GetPollInstancesByCohortAndDays/GetPollInstanceByCohortAndDaysQuery.cs, src/Eras.Application/Features/PollInstances/Queries/GetPollInstancesByCohortAndDays/GetPollInstanceByCohortAndDaysQueryHandler.cs, src/Eras.Application/Features/Polls/Queries/GetPollsByCohort/GetPollsByCohortListQuery.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/PollInstanceRepository.cs, test/Eras.Api.Tests/Controllers/PollInstanceControllerTests.cs, test/Eras.Application.Tests/Features/PollInstances/Commands/CreatePollInstanceCommandHandlerTests.cs, test/Eras.Application.Tests/Features/PollInstances/Queries/GetPollInstanceQueryHandlerTests.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Repositories/PollInstanceRepositoryTest.cs
Enpoint to get poll instance by cohort id and/or last days.
=> Get poll instances by cohort id and/or last days

src/Eras.Api/Controllers/HeatMapController.cs, src/Eras.Application/Contracts/Persistence/IStudentRepository.cs, src/Eras.Application/Eras.Application.csproj, src/Eras.Application/Features/HeatMap/Queries/GetHeatMapDetailsByCohort/GetHeatMapDetailsByCohortQuery.cs, src/Eras.Application/Features/HeatMap/Queries/GetHeatMapDetailsByCohort/GetHeatMapDetailsByCohortQueryHandler.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/StudentRepository.cs, test/Eras.Application.Tests/Eras.Application.Tests.csproj, test/Eras.Application.Tests/Heatmap/Queries/GetHeatMapDetailsByCohort/GetHeatMapDetailsByCohortQueryHandlerTests.cs
- Added GetHeatMapDetailsByCohortQuery and its handler to retrieve top risk students by cohort
- Updated IStudentRepository and implemented GetStudentHeatMapDetailsByCohort in StudentRepository to filter by cohort
- Extended HeatMapController with a new GET endpoint: /api/v1/heatmap/cohort/{cohortId}/top-risk.
- Added unit tests for the new query handler
https://github.com/JU-DEV-Bootcamps/ERAS/issues/73
=> Feat/eras be 73/heatmap by cohort top students

src/Eras.Api/Controllers/ReportsController.cs, src/Eras.Application/Contracts/Persistence/IPollVariableRepository.cs, src/Eras.Application/Features/Consolidator/Queries/GetHigherRiskStudent/GetHigherRiskStudentByPollQuery.cs, src/Eras.Application/Features/Consolidator/Queries/GetHigherRiskStudent/GetHigherRiskStudentByPollQueryHandler.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/PollVariableRepository.cs
An endpoint was created to obtain the list of students with an average of their risk depending on the answers they answered.
=> Create an endpoint for the student risk list

test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/AnswerMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/ComponentMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/EvaluationMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/EvaluationPollMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/PollInstanceMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/PollMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/PollVariableMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/StudentDetailMapperTest.cs, test/Eras.Infrastructure.Tests/Persistence/PostgreSQL/Mappers/StudentMapperTest.cs
=> Unit Tests

src/Eras.Application/Features/Students/Commands/CreateStudent/CreateStudentsCommandHandler.cs, src/Eras.Application/Features/Students/Queries/GetStudentDetails/GetStudentDetailsQueryHandler.cs, src/Eras.Application/Features/StudentsDetails/Commands/CreateStudentDetail/CreateStudentDetailCommandHandler.cs, src/Eras.Application/Features/StudentsDetails/Queries/GetStudentDetailByStudentId/GetStudentDetailByStudentIdQuery.cs, src/Eras.Application/Features/StudentsDetails/Queries/GetStudentDetailByStudentId/GetStudentDetailByStudentIdQueryHandler.cs, src/Eras.Application/Services/PollOrchestratorService.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/StudentDetailRepository.cs
=> Fix Import CSV and restricted import Cl

src/Eras.Api/Controllers/EvaluationController.cs, src/Eras.Application/Features/Evaluations/Queries/GetAll/GetAllEvaluationsQueryHandler.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/EvaluationRepository.cs
=> Get polls when GET paged evaluations

src/Eras.Infrastructure/External/CosmicLatteClient/CosmicLatteAPIService.cs
=> Update pathevaluation constant with the correct url

.editorconfig, .github/workflows/format-warning-check.yaml, src/Eras.Api/Controllers/HeatMapController.cs, test/Eras.Api.Tests/Controllers/HeatMapControllerTests.cs
=> Test format and build checker: Linter

src/Eras.Api/Controllers/CosmicLatteController.cs, src/Eras.Application/DTOs/CosmicLatte/CLEvaluationSetDTO.cs, src/Eras.Application/Features/Students/Commands/CreateStudent/CreateStudentsCommandHandler.cs, src/Eras.Application/Services/PollOrchestratorService.cs, src/Eras.Infrastructure/External/CosmicLatteClient/CosmicLatteAPIService.cs, test/Eras.Api.Tests/Controllers/CosmicLatteControllerTest.cs
Added more validations and fixing some features on import from CL
https://github.com/JU-DEV-Bootcamps/ERAS/issues/121
=> Fix import CL

src/Eras.Api/Program.cs, src/Eras.Application/DTOs/Views/ErasCalculationsByPollDTO.cs, src/Eras.Application/Features/HeatMap/Queries/GetHeatMapSummary/GetHeatMapSummaryHandler.cs, src/Eras.Application/Mappers/HeatMapMapper.cs, src/Eras.Application/Models/Response/HeatMap/GetHeatMapAnswersPercentageByVariableQueryResponse.cs, src/Eras.Domain/Entities/Views/ErasCalculationsByPoll.cs, src/Eras.Infrastructure/Eras.Infrastructure.csproj, src/Eras.Infrastructure/Persistence/PostgreSQL/AppDbContext.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Configurations/ErasCalculationByPollConfiguration.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Entities/ErasCalculationsByPollEntity.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/HeatMapRespository.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Views/vErasCalculationByPoll.sql, test/Eras.Application.Tests/Features/Heatmap/Queries/GetHeatmapSummaryAvgByPoll/GetHeatmapSummaryAvgByPollTests.cs
created the view with all the calculations made and created the configurations and dbset to be used, example usage it's implemented to percentage per answer heatmap report
=> feat(ERAS-130): created the view with all the calculations made 

src/Eras.Application/Features/HeatMap/Queries/GetHeatMapSummary/GetHeatMapSummaryHandler.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/HeatMapRespository.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Views/vErasCalculationByPoll.sql
Just some suggestions on the view column names. Please take a look and feedback.
=> Updated on the sql view

src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/PollInstanceRepository.cs
Change AvgPoolReport to show lower to high risk order.
=> Changed order by to show higher risk last

src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/PollCohortRepository.cs
changed the backend to round the results instead of changing the FE
[ERAS-FE: #201](https://github.com/JU-DEV-Bootcamps/ERAS-FE/issues/201)
=> refactor(ERAS-201): changed the backend to round the results instead of changing the FE

src/Eras.Application/Models/Response/Calculations/GetCohortTopRiskStudentsByComponentResponse.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/CohortRepository.cs
updated the repository to handle the answer average
[ERAS-FE: 196](https://github.com/JU-DEV-Bootcamps/ERAS-FE/issues/196)
=> feat(ERAS196): updated the repository to handle the answer average

src/Eras.Api/Controllers/CohortsController.cs, src/Eras.Api/Controllers/ReportsController.cs, src/Eras.Api/Controllers/StudentsController.cs, src/Eras.Application/Contracts/Persistence/ICohortRepository.cs, src/Eras.Application/Contracts/Persistence/IPollInstanceRepository.cs, src/Eras.Application/DTOs/Views/ErasCalculationsByPollDTO.cs, src/Eras.Application/Features/Cohort/Queries/GetCohortTopRiskStudents/GetCohortTopRiskStudentsQuery.cs, src/Eras.Application/Features/Cohort/Queries/GetCohortTopRiskStudents/GetCohortTopRiskStudentsQueryHandler.cs, src/Eras.Application/Features/Cohort/Queries/GetCohortTopRiskStudentsByComponent/GetCohortTopRiskStudentsByComponentQuery.cs, src/Eras.Application/Features/Cohort/Queries/GetCohortTopRiskStudentsByComponent/GetCohortTopRiskStudentsByComponentQueryHandler.cs, src/Eras.Application/Features/Cohort/Queries/GetCohortsList/GetCohortsListQuery.cs, src/Eras.Application/Features/Cohort/Queries/GetCohortsList/GetCohortsListQueryHandler.cs, src/Eras.Application/Features/Consolidator/Queries/Polls/GetPollCountQuery.cs, src/Eras.Application/Features/Consolidator/Queries/Polls/GetPollCountQueryHandler.cs, src/Eras.Application/Models/Consolidator/TopConsolidatorResponseVm.cs, src/Eras.Domain/Entities/Variable.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/CohortRepository.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/PollInstanceRepository.cs, src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/VariableRepository.cs
- GetCohorts accept query filter of poll Uuid
- Improved naming and signature of cohortrepository methods
- GetVariables includes the componentNames instead of type which is not related to neither the domain or persistence entity
=> Update getCohorts to filter by poll uuid

src/Eras.Application/Features/Polls/Queries/GetAllPollsQuery/GetAllPollsQuery.cs, src/Eras.Application/Features/Polls/Queries/GetAllPollsQuery/GetAllPollsQueryHandler.cs, src/Eras.Application/Features/Polls/Queries/GetPollsByCohort/GetPollsByCohortListQuery.cs, src/Eras.Application/Features/Polls/Queries/GetPollsByCohort/GetPollsByCohortListQueryHandler.cs, src/Eras.Application/Features/Polls/Queries/GetPollsByStudent/GetPollsByStudentQuery.cs, src/Eras.Application/Features/Polls/Queries/GetPollsByStudent/GetPollsByStudentQueryHandler.cs, src/Eras.Application/Features/Students/Queries/GetAll/GetAllStudentsQuery.cs, src/Eras.Application/Features/Students/Queries/GetAll/GetAllStudentsQueryHandler.cs, src/Eras.Application/Models/Response/Controllers/PollsController/GetPollsQueryResponse.cs, src/Eras.Application/Models/Response/Controllers/StudentsController/GetAllStudentsQueryResponse.cs
updated the response models for students and polls, just the sensitive data has been removed and created new models for specific responses
[ERAS-163](https://github.com/JU-DEV-Bootcamps/ERAS/issues/163)
=> refactor(ERAS-163): updated the response models for students and polls

README.md
=> fix(docs): adding test command (test)

.github/workflows/push_workflow.yaml
=> refactor: adding env to workflow

.github/workflows/push_workflow.yaml, src/Eras.Api/appsettings.Production.json, src/Eras.Api/appsettings.json, src/Eras.Infrastructure/InfrastructureServiceRegistration.cs
=> fix: fixing audience issue

src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/StudentRepository.cs
=> fix(Student list is not alphabetically arranged)

src/Eras.Infrastructure/External/CosmicLatteClient/CosmicLatteAPIService.cs
=> fix: adding top filter for api cosmic latte

src/Eras.Application/Utils/StudentValidator.cs
Prevent special characters from appearing in student names **#338**
=> fix(CreateStudentsCommand): add student validators

src/Eras.Application/DTOs/CohortDTO.cs, src/Eras.Application/DTOs/ComponentDTO.cs, src/Eras.Application/DTOs/ConfigurationsDTO.cs, src/Eras.Application/DTOs/HeatMap/HeatMapBaseDataRequestDto.cs, src/Eras.Application/DTOs/ServiceProvidersDTO.cs, src/Eras.Application/DTOs/StudentDetailDTO.cs, src/Eras.Application/DTOs/StudentImportDto.cs, src/Eras.Application/DTOs/VariableDTO.cs, src/Eras.Application/Dtos/AnswerDTO.cs, src/Eras.Application/Dtos/PollDTO.cs, src/Eras.Application/Dtos/StudentDTO.cs
=> fix(Data layer is not validated arranged) #174

src/Eras.Application/Attributes/NoSqlInjectionAttribute.cs, src/Eras.Application/DTOs/CohortDTO.cs, src/Eras.Application/DTOs/ComponentDTO.cs, src/Eras.Application/DTOs/VariableDTO.cs, src/Eras.Application/Dtos/AnswerDTO.cs, src/Eras.Application/Dtos/PollDTO.cs, src/Eras.Application/Dtos/StudentDTO.cs, src/Eras.Application/Utils/SqlInjectionValidator.cs, src/Eras.Infrastructure/External/CosmicLatteClient/CosmicLatteAPIService.cs
- Replaced restrictive character validations with SQL injection protection
- Improve validation logic to ensure consistency across DTOs
=> Fixed 400 validation errors preventing poll imports from CosmicLatte
